# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-02 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('pet_name', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(default='0', max_length=128, primary_key=True, serialize=False, verbose_name='user_name')),
                ('email', models.CharField(default='0', max_length=128, unique=True, verbose_name='email')),
                ('password', models.IntegerField(default=1)),
                ('friends', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petdata.User')),
            ],
        ),
        migrations.CreateModel(
            name='Pet_State',
            fields=[
                ('Pet_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='petdata.Pet')),
                ('pet_hunger', models.IntegerField(default=100)),
                ('pet_clean', models.IntegerField(default=100)),
                ('pet_love', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petdata.User'),
        ),
    ]
