# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-02 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petdata', '0002_auto_20180602_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petdata.User'),
        ),
        migrations.AlterField(
            model_name='pet_state',
            name='pet_clean',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='pet_state',
            name='pet_hunger',
            field=models.IntegerField(default=100),
        ),
    ]
